apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
data:
  myvalue: "Hello World"
  food: {{ .Values.favorite.food | quote }}
  drink: {{ .Values.favorite.drink  }}
