apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: demo-store
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: k8s-secret
      version: "1"

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-2
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: demo-store
    kind: SecretStore
  target:
    name: secret-multiple-values
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s-secret
        version: "3"
