apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-store
  namespace: demo
spec:
  provider:
    gcpsm:
      projectID: org-tools-458804
      auth:
        workloadIdentity:
          clusterLocation: asia-southeast1-a
          clusterName: k8s-cluster-tools
          serviceAccountRef:
            name: demo-secrets-sa