apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-2-repos
  name: frontend-2-repos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-2-repos
  template:
    metadata:
      labels:
        app: frontend-2-repos
    spec:
      containers:
      - imagePullPolicy: Always
        image: asia-southeast1-docker.pkg.dev/web-app-hosting-lehai/web-frontend-repo/frontend-react-app:ga-0.0.9
        name: frontend
        env: 
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: BACKEND_URL
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "0.2"
            memory: "0.5G"
          limits:
            cpu: "0.5"
            memory: "2G"
