apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
  namespace: argocd
spec:
  project: default
  source:
    chart: kestra
    repoURL: https://helm.kestra.io/
    targetRevision: 0.22.4
    helm:
      releaseName: kestra
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd-app