apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kestra-custom-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kestra-service
          servicePort: 8080

