datasources:
  postgres:
    url: jdbc:postgresql://34.42.27.164:5432/kestra
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
kestra:
  server:
    basicAuth:
      enabled: false
      username: admin@localhost.dev
      password: kestra
  repository:
    type: postgres
  storage:
    type: local
    local:
      basePath: /app/storage
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/