

configOverrides:
  secret: |
    SECRET_KEY = 'pqcfnVMAAuzKKQewuLu0qEL+2/VWfynQP7xCgs1LuymQaQriOonpOGfH'

bootstrapScript: |
  #!/bin/bash
  
  # Install system-level dependencies
  apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

  # Install required Python packages
  pip install \
    authlib \
    psycopg2 \
    mysqlclient \

  # Create bootstrap file if it doesn't exist
  if [ ! -f ~/bootstrap ]; then
    echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
  fi

ingress:
  enabled: true
  hosts:
    - superset.haile.click  # Change to your domain
  path: /
  ingressClassName: nginx  # Change if using a different ingress controller
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"  # If using TLS with cert-manager
  tls:
    - hosts:
        - superset.haile.click  # Change to your domain
      secretName: superset-tls