apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: key                           # data field to populate
      objectName: secret                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: foo-secret                     # name of the Kubernetes Secret object
    type: Opaque  
  parameters:
    secrets: |
      - resourceName: "projects/721312990025/secrets/k8s-secret/versions/1"
        path: "secret"
